monitoringagent/src/main/java/io/github/cloudiator/persistance/MTagModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MTagModelConverter.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MTagModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MTagModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelConverter.java

fixed PersitanceConverter with StringMap

persistanceConverterFix

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/resources/logback.xml

first simple threaded installer
add ems-client to installRequest

Addemsagent

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/DeleteMonitorListener.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepositoryJpa.java

summery:
* add deleteAll - functionality - called by using DEL with metric 666
* cleaned logging and old code
* add retryer for connectioncheck with visor before sending config via POST

Threaded visor installation

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/DeleteMonitorListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/GetMonitorListener.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java

adapt getMonitor and deleteMonitor to RestApiChange

changed get and del

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/MonitoringAgent.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/converter/MonitorToVisorMonitorConverter.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/DeleteMonitorListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/GetMonitorListener.java

deleted a testhack
corrected some loggeroutput
corrected VisorMonitorConverter

Get visor monitors

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/converter/MonitorToVisorMonitorConverter.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/NodeEventListener.java
monitoringagent/src/main/resources/logback.xml

Add node events

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelConverter.java

Reverts cloudiator/monitoring#14

Revert "Uuidfix"

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/converter/MonitorToVisorMonitorConverter.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/NodeEventListener.java
monitoringagent/src/main/resources/logback.xml

Reverts cloudiator/monitoring#13

Revert "Add node events"

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/VisorMonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/ConfigurationModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java

- [quickfix] add short delay in threaded monitorgeneration
- changed location of db-metric-generation
- add metric in ErrorMessage

Visorconnection

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelConverter.java

changed some functions to minimize transactional annotation

Dbinteraction

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java

using transactional in DomainRepository

reduceToRepo

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/resources/META-INF/persistence.xml

set Transactional one step earlier
add hibernate properties

changed transactional+hibernate

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java

handlenewMonitor() is now synchronized

syncronized

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java

transfered synchronized and transactional to other methods

changed synchrnized

---

monitoringagent/src/main/java/io/github/cloudiator/persistance/BaseModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/BaseModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/DataSinkModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/DataSinkModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/DataSinkModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/IntervalModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/IntervalModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/IntervalModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitoringBaseModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/PullSensorModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/PullSensorModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/PushSensorModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/PushSensorModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/SensorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/TargetModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/TargetModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/TargetModelRepositoryJpa.java

created own basic classes for Models and Repositories to
separate monitoring-Persistence from common-Persistence basic classes
now changes in Monitoring-Persistence doesn't affect the common-dependencies

changedBasicClasses

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/config/MonitorConfigModule.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/config/MonitorContext.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/resources/reference.conf

added melodicflag in reference.conf:
monitoring.install.melodic.tools = false

Addmelodicflag

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/Init.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/MonitoringAgent.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/config/MonitorConfigModule.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/config/MonitorContext.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/ProcessEventListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/UpdateMonitorListener.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepositoryJpa.java
monitoringagent/src/main/resources/reference.conf

added Methods to use updateMonitor in RestApi
add Eventhandling for Node- and ProcessEvents

Event listener

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/BasicMonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorOrchestrationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/NodeEventListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/ProcessEventListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/models/TargetState.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorDomainRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepository.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelRepositoryJpa.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/StateType.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/StateTypeConverter.java

corrected EventHandling:
- using common updatefunction for all Types of Events
- added FINISHED State
- fixed deleteMonitor function

Event handling

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java

add ProcessUpdate by Monitorgeneration

add processupdate

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueueController.java

synchronized test

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/MonitoringAgent.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorHandler.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorManagementService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueueConsumer.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueueController.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorSynchronizationService.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/NodeEventListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/ProcessEventListener.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/models/DomainMonitorModel.java
monitoringagent/src/main/java/io/github/cloudiator/persistance/MonitorModelConverter.java

Queue controller

---

monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueue.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueueConsumer.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/domain/MonitorQueueController.java
monitoringagent/src/main/java/io/github/cloudiator/monitoring/messaging/ProcessEventListener.java

added ExceptionHandling in MonitorQueueConsumers

Exceptionhandling in Consumers
